---
Jenkins:
  hosts:
    aws:
       ansible_host: 100.27.49.28
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "/home/dlearn/Final-Version/terraform/depi"
    ansible_connection: ssh
    ansible_port: "22" 
