---
Jenkins:
  hosts:
    rocky:
      ansible_host: XXXXXXX #nexus node  IP
  vars:
    ansible_user:  XXXX #Ceate a User On worker node
    ansible_ssh_private_key_file: ~/.ssh/id_rsa #Private Key From Terrafrom File Path
    ansible_connection: ssh
    ansible_port: "22"