---
- name: Create all required username-password credentials entities.
  jenkins_script:
    script: "{{ lookup('template', 'templates/cred.groovy') }}"
    url: 'http://{{ jenkins_url }}'
    user: '{{ jenkins_admin_username }}'
    password: '{{ jenkins_admin_password }}'
  #tags:
  #  - Remote_Jenkins
  with_items: '{{ credentials }}'
  no_log: true