---
- name: Uninstall Java on Red Hat/CentOS
  package:
    name: java
    state: absent
  when: ansible_distribution in ["RedHat", "CentOS"]

- name: Uninstall Java (OpenJDK) on Amazon Linux
  package:
    name: java-22-amazon-corretto
    state: absent
  when: ansible_distribution == "Amazon"

- name : Adding java on rhel distro
  package:
      name: "{{java.rhel_version}}"
      state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution != "Amazon" 


- name: Adding java on aws distro
  dnf:
    name: "{{ java.packages }}"
    state:  latest 
    update_cache: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution == "Amazon" 

- name: Set Java HOME
  lineinfile: 
          path: "{{ java.path }}"
          line: "{{item}}"
          state: present
  loop:
        - JAVA_HOME="{{ java.JAVA_HOME }}"
        - export JAVA_HOME
        - PATH=$PATH:$JAVA_HOME


- name: Add Java 17 to alternatives system
  command: |
    update-alternatives --install /usr/bin/java java /usr/lib/jvm/jre-17-openjdk/bin/java 1
  when: ansible_distribution in ["Ubuntu", "Debian", "Amazon", "RedHat", "CentOS"]

- name: Set Java 17 as the default version
  command: |
    update-alternatives --set java /usr/lib/jvm/jre-17-openjdk/bin/java
  when: ansible_distribution in ["Ubuntu", "Debian", "Amazon", "RedHat", "CentOS"]

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget 
    - fontconfig
    - git

- name: Create yum directory
  file:
        path: "{{yum.path}}"
        state: directory

- name: Make yum repo
  yum_repository:
        name: jenkins
        baseurl: "{{jenkins.rpm_url}}"
        description: jenkins yum repo
        gpgcheck: yes 
        gpgkey: "{{yum.key}}"
        enabled: 1
        
- name:  Updating cache
  dnf:
    update_cache: true

- name: Install jenkins
  yum:
   name: jenkins
   state: present

- name: Jenkins starting
  service:
   name: jenkins
   state: started
   enabled : yes